import{a as w,S as B,i as a}from"./assets/vendor-DxEWe7lX.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const v="50384858-0b7fb3bc045111b4da7b5b4d8",I="https://pixabay.com/api/";async function f(o,t=1){const n={key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};try{return(await w.get(I,{params:n})).data}catch{throw new Error("Error fetching images")}}const u=document.getElementById("gallery"),m=document.getElementById("loader"),g=document.getElementById("load-more");let P=new B(".gallery a");function h(o){const t=o.map(({webformatURL:n,largeImageURL:s,tags:e,likes:r,views:i,comments:L,downloads:E})=>`
    <li class="photo-card">
      <a href="${s}">
        <img src="${n}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${r}</p>
        <p class="info-item"><b>Views:</b> ${i}</p>
        <p class="info-item"><b>Comments:</b> ${L}</p>
        <p class="info-item"><b>Downloads:</b> ${E}</p>
      </div>
    </li>
  `).join("");u.insertAdjacentHTML("beforeend",t),P.refresh()}function $(){u.innerHTML=""}function y(){m.classList.remove("hidden")}function p(){m.classList.add("hidden")}function M(){g.classList.remove("hidden")}function b(){g.classList.add("hidden")}const q=document.getElementById("search-form"),H=document.getElementById("load-more");let c="",l=1,d=0;q.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.target.elements.searchQuery.value.trim(),!c){a.warning({title:"Warning",message:"Please enter a search query"});return}l=1,$(),b(),y();try{const t=await f(c,l);if(d=t.totalHits,t.hits.length===0){a.info({title:"Info",message:"No images found. Please try another query."});return}h(t.hits),a.success({title:"Success",message:`Hooray! We found ${d} images.`}),d>15&&M()}catch{a.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{p()}});H.addEventListener("click",async()=>{l+=1,y();try{const o=await f(c,l);h(o.hits);const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),l*15>=d&&(b(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({title:"Error",message:"Failed to fetch more images. Please try again later."})}finally{p()}});
//# sourceMappingURL=index.js.map
