import{a as w,S as L,i as c}from"./assets/vendor-CocXUmuy.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const v="50384858-0b7fb3bc045111b4da7b5b4d8",S="https://pixabay.com/api/";async function q(t,r=1){const s={key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};try{return(await w.get(S,{params:s})).data}catch{throw new Error("Error fetching images")}}const d=document.querySelector(".gallery"),p=document.querySelector(".loader"),m=document.querySelector(".load-more"),B=new L(".gallery a",{captionsData:"alt",captionDelay:250});function C(t){const r=t.map(s=>{const{webformatURL:i,largeImageURL:e,tags:o,likes:n,views:g,comments:h,downloads:b}=s;return`
      <li class="gallery-item">
        <a href="${e}"><img class="gallery-image" src="${i}" alt="${o}"/></a>
        <div class="stats">
          <p><span>Likes</span><span>${n}</span></p>
          <p><span>Views</span><span>${g}</span></p>
          <p><span>Comments</span><span>${h}</span></p>
          <p><span>Downloads</span><span>${b}</span></p>
        </div>
      </li>
        `}).join("");d.insertAdjacentHTML("beforeend",r),B.refresh()}function M(){d.innerHTML=""}function $(){p.style.visibility="visible"}function E(){p.style.visibility="hidden"}function P(){m.style.visibility="visible"}function f(){m.style.visibility="hidden"}const I=document.querySelector(".form"),O=document.querySelector(".load-more");let a,l=1;const u=15;I.addEventListener("submit",t=>{t.preventDefault(),f(),M(),a=t.target.elements["search-text"].value.trim(),a&&(l=1,y(a))});O.addEventListener("click",t=>{f(),l++,y(a),R()});async function y(t){$();try{const r=await q(t,l,u),s=r.hits;s&&s.length>0?(C(s),l>=Math.ceil(r.totalHits/u)?c.show({title:"ℹ️",message:"We're sorry, but you've reached the end of search results.",messageColor:"white",titleColor:"white",backgroundColor:"#4CAF50",position:"topRight"}):P()):c.show({title:"❌",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",titleColor:"white",backgroundColor:"#ef4040",position:"topRight"})}catch(r){console.error(r)}finally{E()}}function R(){const t=document.querySelector(".gallery-item");t&&setTimeout(()=>{scrollBy({top:t.getBoundingClientRect().height*2,left:0,behavior:"smooth"})},200)}
//# sourceMappingURL=index.js.map
